Make service-worker-status more obviously dynamic
hoodiehq/hoodie-camp-tutorial pull request #21
Opened 2016-10-06 04:01 UTC by IanDCarroll

The service-worker-status class above the code on page 1 is not intuitively understood as a dynamic element. When I first read it, I skimmed right over it and assumed it was just some styled text.

By giving status its own paragraph, centering it and putting a simple border around the element, it will me more easy for humans to interpret it as dynamic. And important.

![service-worker-status](https://cloud.githubusercontent.com/assets/14797009/19140089/c085afb2-8b3e-11e6-8950-882f909fd20a.png)

2016-10-06 04:31 UTC, gr2m requested changes

2016-10-06 04:31 UTC, gr2m commented on public/assets/css/main.css
> +  display: block;i
can you remove this `i`?

2016-10-06 04:31 UTC, gr2m commented on public/assets/css/main.css
> +}
can you replace `.service-worker-status` with `.service-worker-status-text strong`

2016-10-06 04:40 UTC, IanDCarroll commented on public/assets/css/main.css
> +}
.service-worker-status is needed for the text status to display :)

2016-10-06 18:28 UTC, merged

2016-10-06 18:29 UTC, gr2m commented
Thanks Ian 👍 Are you on twitter? We like giving shout outs to new contributors, only if you want of course :)

2016-10-07 20:45 UTC, IanDCarroll commented
twitter @_IanDCarroll_