docs: Instructions on unregistering ServiceWorker
hoodiehq/hoodie-camp-tutorial pull request #24
Opened 2016-10-11 23:30 UTC by nongaap

2016-10-12 20:06 UTC, gr2m requested changes

2016-10-12 20:06 UTC, gr2m commented on README.md
> +To remove the offline tutorial from [localhost:8080](http://localhost:8080) visit chrome://serviceworker-internals/ if using Chrome or visit about:serviceworkers if using Firefox and unregister the S
can you check out what it is for Microsoft’s Edge browser? Maybe @jameswestnz can help?

2016-10-12 21:17 UTC, nongaap commented on README.md
> +To remove the offline tutorial from [localhost:8080](http://localhost:8080) visit chrome://serviceworker-internals/ if using Chrome or visit about:serviceworkers if using Firefox and unregister the S
@gr2m Edge is currently [in development](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/serviceworker) for Service Worker.

Opera browser supports Service Worker and will add instructions to unregister.

2016-10-13 03:24 UTC, gr2m commented on README.md
> +To remove the offline tutorial from [localhost:8080](http://localhost:8080) visit chrome://serviceworker-internals/ if using Chrome or visit about:serviceworkers if using Firefox and unregister the S
sweet, thanks!

2016-10-13 03:24 UTC, gr2m approved these changes

2016-10-13 03:24 UTC, merged